### ISSUE TITLE
Wrong GVP and GVN responses

### ISSUE THREAD

**Issue by polakovic** [mappite/aGotino#5]
Responses are not ended with '#' and thus protocol dialect detection is not possible.

**Comment by eliboni** [comment]
Peter many thanks for the finding, you're right the final # is missed but it is required as per protocol specs. We'll fix it soon.

**Comment by eliboni** [comment]
Fixed in main

**Comment by eliboni** [comment]
@polakovic the issue is closed since some time but pls if you can confirm it is solved  I would appreciate. Thanks

**Comment by polakovic** [comment]
Unfortunately I don't have such mount so I can't confirm it :(
