### ISSUE TITLE
Figuring out maths for different mounts...

### ISSUE THREAD

**Issue by pepsiaddict82** [mappite/aGotino#6]
Hey I am just wondering about how to go about getting this rather important numbers right, first let me say thanks for your project and I hope to have it figured out here and be able to use it without having to make guesses in setting it all up!

Ok so I have a mount, its an astromaster mount, from what I can gather often times being called an eq2, now I understand its not the best mount to convert, but its what I have, as often is the argument when it comes to DIY stuff :) now then, when trying to figure out the maths,, I am instantly stuck on gathering numbers to input for a couple reasons, hopefully I can get some clarity.

First is the fact that I am direct driving the RA motor, so motor>coupler>RA worm..that spins the large gear on the RA. Question being the worm gear, how does one go about getting a number of teeth here?
For the DEC I have a large and small gear, so thats fine, but documentation doesnt really make things clear, as well the belt calculator you link to is largely irrelevant to most I assume, because this being a DIY project, can probably be safe to assume that mounting of motors is going to vary largely.

I am also quite curious about using the 2209's as drivers, I understand that for the most part these drivers pins are much the same, but just wanted to get a definitive understanding of what to connect where, being that one could argue the 2209 being the most popular driver in the wild today...

Not even sure if youre still doing anything with this project, but I figured I would take a shot and ask here first, rather than a 3rd party site. 

Thanks for your time

**Comment by eliboni** [comment]
I suggest to post this question on CloudyNight/Stargazer  or similar forums where somebody may already know the answers your are looking  for an eq2. One way to find the worm gear ratio is to mark the initial RA position and turn knob n times until the marker is back to the original position (if I remember correctly it could be 1:138). For the driver I can't help much, this is the issue list for agotino code, you'll get more inputs in astronomy diy forums.
